import React, {useState} from 'react';
export const countriesData = [
    {
      name: 'Afghanistan',
      capital: 'Kabul',
      languages: ['Pashto', 'Uzbek', 'Turkmen'],
      population: 27657145,
      flag: 'https://flagcdn.com/afg.svg',
      currency: 'Afghan afghani',
    },
    {
      name: 'Åland Islands',
      capital: 'Mariehamn',
      languages: ['Swedish'],
      population: 28875,
      flag: 'https://flagcdn.com/ala.svg',
      currency: 'Euro',
    },
    {
      name: 'Albania',
      capital: 'Tirana',
      languages: ['Albanian'],
      population: 2886026,
      flag: 'https://flagcdn.com/alb.svg',
      currency: 'Albanian lek',
    },
    {
      name: 'Algeria',
      capital: 'Algiers',
      languages: ['Arabic'],
      population: 40400000,
      flag: 'https://flagcdn.com/dza.svg',
      currency: 'Algerian dinar',
    },
    {
      name: 'American Samoa',
      capital: 'Pago Pago',
      languages: ['English', 'Samoan'],
      population: 57100,
      flag: 'https://flagcdn.com/asm.svg',
      currency: 'United State Dollar',
    },
    {
      name: 'Andorra',
      capital: 'Andorra la Vella',
      languages: ['Catalan'],
      population: 78014,
      flag: 'https://flagcdn.com/and.svg',
      currency: 'Euro',
    },
    {
      name: 'Angola',
      capital: 'Luanda',
      languages: ['Portuguese'],
      population: 25868000,
      flag: 'https://flagcdn.com/ago.svg',
      currency: 'Angolan kwanza',
    },
    {
      name: 'Anguilla',
      capital: 'The Valley',
      languages: ['English'],
      population: 13452,
      flag: 'https://flagcdn.com/aia.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Antarctica',
      capital: '',
      languages: ['English', 'Russian'],
      population: 1000,
      flag: 'https://flagcdn.com/ata.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Antigua and Barbuda',
      capital: "Saint John's",
      languages: ['English'],
      population: 86295,
      flag: 'https://flagcdn.com/atg.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Argentina',
      capital: 'Buenos Aires',
      languages: ['Spanish', 'Guaraní'],
      population: 43590400,
      flag: 'https://flagcdn.com/arg.svg',
      currency: 'Argentine peso',
    },
    {
      name: 'Armenia',
      capital: 'Yerevan',
      languages: ['Armenian', 'Russian'],
      population: 2994400,
      flag: 'https://flagcdn.com/arm.svg',
      currency: 'Armenian dram',
    },
    {
      name: 'Aruba',
      capital: 'Oranjestad',
      languages: ['Dutch', '(Eastern) Punjabi'],
      population: 107394,
      flag: 'https://flagcdn.com/abw.svg',
      currency: 'Aruban florin',
    },
    {
      name: 'Australia',
      capital: 'Canberra',
      languages: ['English'],
      population: 24117360,
      flag: 'https://flagcdn.com/aus.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Austria',
      capital: 'Vienna',
      languages: ['German'],
      population: 8725931,
      flag: 'https://flagcdn.com/aut.svg',
      currency: 'Euro',
    },
    {
      name: 'Azerbaijan',
      capital: 'Baku',
      languages: ['Azerbaijani'],
      population: 9730500,
      flag: 'https://flagcdn.com/aze.svg',
      currency: 'Azerbaijani manat',
    },
    {
      name: 'Bahamas',
      capital: 'Nassau',
      languages: ['English'],
      population: 378040,
      flag: 'https://flagcdn.com/bhs.svg',
      currency: 'Bahamian dollar',
    },
    {
      name: 'Bahrain',
      capital: 'Manama',
      languages: ['Arabic'],
      population: 1404900,
      flag: 'https://flagcdn.com/bhr.svg',
      currency: 'Bahraini dinar',
    },
    {
      name: 'Bangladesh',
      capital: 'Dhaka',
      languages: ['Bengali'],
      population: 161006790,
      flag: 'https://flagcdn.com/bgd.svg',
      currency: 'Bangladeshi taka',
    },
    {
      name: 'Barbados',
      capital: 'Bridgetown',
      languages: ['English'],
      population: 285000,
      flag: 'https://flagcdn.com/brb.svg',
      currency: 'Barbadian dollar',
    },
    {
      name: 'Belarus',
      capital: 'Minsk',
      languages: ['Belarusian', 'Russian'],
      population: 9498700,
      flag: 'https://flagcdn.com/blr.svg',
      currency: 'New Belarusian ruble',
    },
    {
      name: 'Belgium',
      capital: 'Brussels',
      languages: ['Dutch', 'French', 'German'],
      population: 11319511,
      flag: 'https://flagcdn.com/bel.svg',
      currency: 'Euro',
    },
    {
      name: 'Belize',
      capital: 'Belmopan',
      languages: ['English', 'Spanish'],
      population: 370300,
      flag: 'https://flagcdn.com/blz.svg',
      currency: 'Belize dollar',
    },
    {
      name: 'Benin',
      capital: 'Porto-Novo',
      languages: ['French'],
      population: 10653654,
      flag: 'https://flagcdn.com/ben.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Bermuda',
      capital: 'Hamilton',
      languages: ['English'],
      population: 61954,
      flag: 'https://flagcdn.com/bmu.svg',
      currency: 'Bermudian dollar',
    },
    {
      name: 'Bhutan',
      capital: 'Thimphu',
      languages: ['Dzongkha'],
      population: 775620,
      flag: 'https://flagcdn.com/btn.svg',
      currency: 'Bhutanese ngultrum',
    },
    {
      name: 'Bolivia (Plurinational State of)',
      capital: 'Sucre',
      languages: ['Spanish', 'Aymara', 'Quechua'],
      population: 10985059,
      flag: 'https://flagcdn.com/bol.svg',
      currency: 'Bolivian boliviano',
    },
    {
      name: 'Bonaire, Sint Eustatius and Saba',
      capital: 'Kralendijk',
      languages: ['Dutch'],
      population: 17408,
      flag: 'https://flagcdn.com/bes.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Bosnia and Herzegovina',
      capital: 'Sarajevo',
      languages: ['Bosnian', 'Croatian', 'Serbian'],
      population: 3531159,
      flag: 'https://flagcdn.com/bih.svg',
      currency: 'Bosnia and Herzegovina convertible mark',
    },
    {
      name: 'Botswana',
      capital: 'Gaborone',
      languages: ['English', 'Tswana'],
      population: 2141206,
      flag: 'https://flagcdn.com/bwa.svg',
      currency: 'Botswana pula',
    },
    {
      name: 'Bouvet Island',
      capital: '',
      languages: ['Norwegian', 'Norwegian Bokmål', 'Norwegian Nynorsk'],
      population: 0,
      flag: 'https://flagcdn.com/bvt.svg',
      currency: 'Norwegian krone',
    },
    {
      name: 'Brazil',
      capital: 'Brasília',
      languages: ['Portuguese'],
      population: 206135893,
      flag: 'https://flagcdn.com/bra.svg',
      currency: 'Brazilian real',
    },
    {
      name: 'British Indian Ocean Territory',
      capital: 'Diego Garcia',
      languages: ['English'],
      population: 3000,
      flag: 'https://flagcdn.com/iot.svg',
      currency: 'United States dollar',
    },
    {
      name: 'United States Minor Outlying Islands',
      capital: '',
      languages: ['English'],
      population: 300,
      flag: 'https://flagcdn.com/umi.svg',
      currency: 'United States Dollar',
    },
    {
      name: 'Virgin Islands (British)',
      capital: 'Road Town',
      languages: ['English'],
      population: 28514,
      flag: 'https://flagcdn.com/vgb.svg',
      currency: '[D]',
    },
    {
      name: 'Virgin Islands (U.S.)',
      capital: 'Charlotte Amalie',
      languages: ['English'],
      population: 114743,
      flag: 'https://flagcdn.com/vir.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Brunei Darussalam',
      capital: 'Bandar Seri Begawan',
      languages: ['Malay'],
      population: 411900,
      flag: 'https://flagcdn.com/brn.svg',
      currency: 'Brunei dollar',
    },
    {
      name: 'Bulgaria',
      capital: 'Sofia',
      languages: ['Bulgarian'],
      population: 7153784,
      flag: 'https://flagcdn.com/bgr.svg',
      currency: 'Bulgarian lev',
    },
    {
      name: 'Burkina Faso',
      capital: 'Ouagadougou',
      languages: ['French', 'Fula'],
      population: 19034397,
      flag: 'https://flagcdn.com/bfa.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Burundi',
      capital: 'Bujumbura',
      languages: ['French', 'Kirundi'],
      population: 10114505,
      flag: 'https://flagcdn.com/bdi.svg',
      currency: 'Burundian franc',
    },
    {
      name: 'Cambodia',
      capital: 'Phnom Penh',
      languages: ['Khmer'],
      population: 15626444,
      flag: 'https://flagcdn.com/khm.svg',
      currency: 'Cambodian riel',
    },
    {
      name: 'Cameroon',
      capital: 'Yaoundé',
      languages: ['English', 'French'],
      population: 22709892,
      flag: 'https://flagcdn.com/cmr.svg',
      currency: 'Central African CFA franc',
    },
    {
      name: 'Canada',
      capital: 'Ottawa',
      languages: ['English', 'French'],
      population: 36155487,
      flag: 'https://flagcdn.com/can.svg',
      currency: 'Canadian dollar',
    },
    {
      name: 'Cabo Verde',
      capital: 'Praia',
      languages: ['Portuguese'],
      population: 531239,
      flag: 'https://flagcdn.com/cpv.svg',
      currency: 'Cape Verdean escudo',
    },
    {
      name: 'Cayman Islands',
      capital: 'George Town',
      languages: ['English'],
      population: 58238,
      flag: 'https://flagcdn.com/cym.svg',
      currency: 'Cayman Islands dollar',
    },
    {
      name: 'Central African Republic',
      capital: 'Bangui',
      languages: ['French', 'Sango'],
      population: 4998000,
      flag: 'https://flagcdn.com/caf.svg',
      currency: 'Central African CFA franc',
    },
    {
      name: 'Chad',
      capital: "N'Djamena",
      languages: ['French', 'Arabic'],
      population: 14497000,
      flag: 'https://flagcdn.com/tcd.svg',
      currency: 'Central African CFA franc',
    },
    {
      name: 'Chile',
      capital: 'Santiago',
      languages: ['Spanish'],
      population: 18191900,
      flag: 'https://flagcdn.com/chl.svg',
      currency: 'Chilean peso',
    },
    {
      name: 'China',
      capital: 'Beijing',
      languages: ['Chinese'],
      population: 1377422166,
      flag: 'https://flagcdn.com/chn.svg',
      currency: 'Chinese yuan',
    },
    {
      name: 'Christmas Island',
      capital: 'Flying Fish Cove',
      languages: ['English'],
      population: 2072,
      flag: 'https://flagcdn.com/cxr.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Cocos (Keeling) Islands',
      capital: 'West Island',
      languages: ['English'],
      population: 550,
      flag: 'https://flagcdn.com/cck.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Colombia',
      capital: 'Bogotá',
      languages: ['Spanish'],
      population: 48759958,
      flag: 'https://flagcdn.com/col.svg',
      currency: 'Colombian peso',
    },
    {
      name: 'Comoros',
      capital: 'Moroni',
      languages: ['Arabic', 'French'],
      population: 806153,
      flag: 'https://flagcdn.com/com.svg',
      currency: 'Comorian franc',
    },
    {
      name: 'Congo',
      capital: 'Brazzaville',
      languages: ['French', 'Lingala'],
      population: 4741000,
      flag: 'https://flagcdn.com/cog.svg',
      currency: 'Central African CFA franc',
    },
    {
      name: 'Congo (Democratic Republic of the)',
      capital: 'Kinshasa',
      languages: ['French', 'Lingala', 'Kongo', 'Swahili', 'Luba-Katanga'],
      population: 85026000,
      flag: 'https://flagcdn.com/cod.svg',
      currency: 'Congolese franc',
    },
    {
      name: 'Cook Islands',
      capital: 'Avarua',
      languages: ['English'],
      population: 18100,
      flag: 'https://flagcdn.com/cok.svg',
      currency: 'New Zealand dollar',
    },
    {
      name: 'Costa Rica',
      capital: 'San José',
      languages: ['Spanish'],
      population: 4890379,
      flag: 'https://flagcdn.com/cri.svg',
      currency: 'Costa Rican colón',
    },
    {
      name: 'Croatia',
      capital: 'Zagreb',
      languages: ['Croatian'],
      population: 4190669,
      flag: 'https://flagcdn.com/hrv.svg',
      currency: 'Croatian kuna',
    },
    {
      name: 'Cuba',
      capital: 'Havana',
      languages: ['Spanish'],
      population: 11239004,
      flag: 'https://flagcdn.com/cub.svg',
      currency: 'Cuban convertible peso',
    },
    {
      name: 'Curaçao',
      capital: 'Willemstad',
      languages: ['Dutch', '(Eastern) Punjabi', 'English'],
      population: 154843,
      flag: 'https://flagcdn.com/cuw.svg',
      currency: 'Netherlands Antillean guilder',
    },
    {
      name: 'Cyprus',
      capital: 'Nicosia',
      languages: ['Greek (modern)', 'Turkish', 'Armenian'],
      population: 847000,
      flag: 'https://flagcdn.com/cyp.svg',
      currency: 'Euro',
    },
    {
      name: 'Czech Republic',
      capital: 'Prague',
      languages: ['Czech', 'Slovak'],
      population: 10558524,
      flag: 'https://flagcdn.com/cze.svg',
      currency: 'Czech koruna',
    },
    {
      name: 'Denmark',
      capital: 'Copenhagen',
      languages: ['Danish'],
      population: 5717014,
      flag: 'https://flagcdn.com/dnk.svg',
      currency: 'Danish krone',
    },
    {
      name: 'Djibouti',
      capital: 'Djibouti',
      languages: ['French', 'Arabic'],
      population: 900000,
      flag: 'https://flagcdn.com/dji.svg',
      currency: 'Djiboutian franc',
    },
    {
      name: 'Dominica',
      capital: 'Roseau',
      languages: ['English'],
      population: 71293,
      flag: 'https://flagcdn.com/dma.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Dominican Republic',
      capital: 'Santo Domingo',
      languages: ['Spanish'],
      population: 10075045,
      flag: 'https://flagcdn.com/dom.svg',
      currency: 'Dominican peso',
    },
    {
      name: 'Ecuador',
      capital: 'Quito',
      languages: ['Spanish'],
      population: 16545799,
      flag: 'https://flagcdn.com/ecu.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Egypt',
      capital: 'Cairo',
      languages: ['Arabic'],
      population: 91290000,
      flag: 'https://flagcdn.com/egy.svg',
      currency: 'Egyptian pound',
    },
    {
      name: 'El Salvador',
      capital: 'San Salvador',
      languages: ['Spanish'],
      population: 6520675,
      flag: 'https://flagcdn.com/slv.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Equatorial Guinea',
      capital: 'Malabo',
      languages: ['Spanish', 'French'],
      population: 1222442,
      flag: 'https://flagcdn.com/gnq.svg',
      currency: 'Central African CFA franc',
    },
    {
      name: 'Eritrea',
      capital: 'Asmara',
      languages: ['Tigrinya', 'Arabic', 'English'],
      population: 5352000,
      flag: 'https://flagcdn.com/eri.svg',
      currency: 'Eritrean nakfa',
    },
    {
      name: 'Estonia',
      capital: 'Tallinn',
      languages: ['Estonian'],
      population: 1315944,
      flag: 'https://flagcdn.com/est.svg',
      currency: 'Euro',
    },
    {
      name: 'Ethiopia',
      capital: 'Addis Ababa',
      languages: ['Amharic'],
      population: 92206005,
      flag: 'https://flagcdn.com/eth.svg',
      currency: 'Ethiopian birr',
    },
    {
      name: 'Falkland Islands (Malvinas)',
      capital: 'Stanley',
      languages: ['English'],
      population: 2563,
      flag: 'https://flagcdn.com/flk.svg',
      currency: 'Falkland Islands pound',
    },
    {
      name: 'Faroe Islands',
      capital: 'Tórshavn',
      languages: ['Faroese'],
      population: 49376,
      flag: 'https://flagcdn.com/fro.svg',
      currency: 'Danish krone',
    },
    {
      name: 'Fiji',
      capital: 'Suva',
      languages: ['English', 'Fijian', 'Hindi', 'Urdu'],
      population: 867000,
      flag: 'https://flagcdn.com/fji.svg',
      currency: 'Fijian dollar',
    },
    {
      name: 'Finland',
      capital: 'Helsinki',
      languages: ['Finnish', 'Swedish'],
      population: 5491817,
      flag: 'https://flagcdn.com/fin.svg',
      currency: 'Euro',
    },
    {
      name: 'France',
      capital: 'Paris',
      languages: ['French'],
      population: 66710000,
      flag: 'https://flagcdn.com/fra.svg',
      currency: 'Euro',
    },
    {
      name: 'French Guiana',
      capital: 'Cayenne',
      languages: ['French'],
      population: 254541,
      flag: 'https://flagcdn.com/guf.svg',
      currency: 'Euro',
    },
    {
      name: 'French Polynesia',
      capital: 'Papeetē',
      languages: ['French'],
      population: 271800,
      flag: 'https://flagcdn.com/pyf.svg',
      currency: 'CFP franc',
    },
    {
      name: 'French Southern Territories',
      capital: 'Port-aux-Français',
      languages: ['French'],
      population: 140,
      flag: 'https://flagcdn.com/atf.svg',
      currency: 'Euro',
    },
    {
      name: 'Gabon',
      capital: 'Libreville',
      languages: ['French'],
      population: 1802278,
      flag: 'https://flagcdn.com/gab.svg',
      currency: 'Central African CFA franc',
    },
    {
      name: 'Gambia',
      capital: 'Banjul',
      languages: ['English'],
      population: 1882450,
      flag: 'https://flagcdn.com/gmb.svg',
      currency: 'Gambian dalasi',
    },
    {
      name: 'Georgia',
      capital: 'Tbilisi',
      languages: ['Georgian'],
      population: 3720400,
      flag: 'https://flagcdn.com/geo.svg',
      currency: 'Georgian Lari',
    },
    {
      name: 'Germany',
      capital: 'Berlin',
      languages: ['German'],
      population: 81770900,
      flag: 'https://flagcdn.com/deu.svg',
      currency: 'Euro',
    },
    {
      name: 'Ghana',
      capital: 'Accra',
      languages: ['English'],
      population: 27670174,
      flag: 'https://flagcdn.com/gha.svg',
      currency: 'Ghanaian cedi',
    },
    {
      name: 'Gibraltar',
      capital: 'Gibraltar',
      languages: ['English'],
      population: 33140,
      flag: 'https://flagcdn.com/gib.svg',
      currency: 'Gibraltar pound',
    },
    {
      name: 'Greece',
      capital: 'Athens',
      languages: ['Greek (modern)'],
      population: 10858018,
      flag: 'https://flagcdn.com/grc.svg',
      currency: 'Euro',
    },
    {
      name: 'Greenland',
      capital: 'Nuuk',
      languages: ['Kalaallisut'],
      population: 55847,
      flag: 'https://flagcdn.com/grl.svg',
      currency: 'Danish krone',
    },
    {
      name: 'Grenada',
      capital: "St. George's",
      languages: ['English'],
      population: 103328,
      flag: 'https://flagcdn.com/grd.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Guadeloupe',
      capital: 'Basse-Terre',
      languages: ['French'],
      population: 400132,
      flag: 'https://flagcdn.com/glp.svg',
      currency: 'Euro',
    },
    {
      name: 'Guam',
      capital: 'Hagåtña',
      languages: ['English', 'Chamorro', 'Spanish'],
      population: 184200,
      flag: 'https://flagcdn.com/gum.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Guatemala',
      capital: 'Guatemala City',
      languages: ['Spanish'],
      population: 16176133,
      flag: 'https://flagcdn.com/gtm.svg',
      currency: 'Guatemalan quetzal',
    },
    {
      name: 'Guernsey',
      capital: 'St. Peter Port',
      languages: ['English', 'French'],
      population: 62999,
      flag: 'https://flagcdn.com/ggy.svg',
      currency: 'British pound',
    },
    {
      name: 'Guinea',
      capital: 'Conakry',
      languages: ['French', 'Fula'],
      population: 12947000,
      flag: 'https://flagcdn.com/gin.svg',
      currency: 'Guinean franc',
    },
    {
      name: 'Guinea-Bissau',
      capital: 'Bissau',
      languages: ['Portuguese'],
      population: 1547777,
      flag: 'https://flagcdn.com/gnb.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Guyana',
      capital: 'Georgetown',
      languages: ['English'],
      population: 746900,
      flag: 'https://flagcdn.com/guy.svg',
      currency: 'Guyanese dollar',
    },
    {
      name: 'Haiti',
      capital: 'Port-au-Prince',
      languages: ['French', 'Haitian'],
      population: 11078033,
      flag: 'https://flagcdn.com/hti.svg',
      currency: 'Haitian gourde',
    },
    {
      name: 'Heard Island and McDonald Islands',
      capital: '',
      languages: ['English'],
      population: 0,
      flag: 'https://flagcdn.com/hmd.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Holy See',
      capital: 'Rome',
      languages: ['Latin', 'Italian', 'French', 'German'],
      population: 451,
      flag: 'https://flagcdn.com/vat.svg',
      currency: 'Euro',
    },
    {
      name: 'Honduras',
      capital: 'Tegucigalpa',
      languages: ['Spanish'],
      population: 8576532,
      flag: 'https://flagcdn.com/hnd.svg',
      currency: 'Honduran lempira',
    },
    {
      name: 'Hong Kong',
      capital: 'City of Victoria',
      languages: ['English', 'Chinese'],
      population: 7324300,
      flag: 'https://flagcdn.com/hkg.svg',
      currency: 'Hong Kong dollar',
    },
    {
      name: 'Hungary',
      capital: 'Budapest',
      languages: ['Hungarian'],
      population: 9823000,
      flag: 'https://flagcdn.com/hun.svg',
      currency: 'Hungarian forint',
    },
    {
      name: 'Iceland',
      capital: 'Reykjavík',
      languages: ['Icelandic'],
      population: 334300,
      flag: 'https://flagcdn.com/isl.svg',
      currency: 'Icelandic króna',
    },
    {
      name: 'India',
      capital: 'New Delhi',
      languages: ['Hindi', 'English'],
      population: 1295210000,
      flag: 'https://flagcdn.com/ind.svg',
      currency: 'Indian rupee',
    },
    {
      name: 'Indonesia',
      capital: 'Jakarta',
      languages: ['Indonesian'],
      population: 258705000,
      flag: 'https://flagcdn.com/idn.svg',
      currency: 'Indonesian rupiah',
    },
    {
      name: "Côte d'Ivoire",
      capital: 'Yamoussoukro',
      languages: ['French'],
      population: 22671331,
      flag: 'https://flagcdn.com/civ.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Iran (Islamic Republic of)',
      capital: 'Tehran',
      languages: ['Persian (Farsi)'],
      population: 79369900,
      flag: 'https://flagcdn.com/irn.svg',
      currency: 'Iranian rial',
    },
    {
      name: 'Iraq',
      capital: 'Baghdad',
      languages: ['Arabic', 'Kurdish'],
      population: 37883543,
      flag: 'https://flagcdn.com/irq.svg',
      currency: 'Iraqi dinar',
    },
    {
      name: 'Ireland',
      capital: 'Dublin',
      languages: ['Irish', 'English'],
      population: 6378000,
      flag: 'https://flagcdn.com/irl.svg',
      currency: 'Euro',
    },
    {
      name: 'Isle of Man',
      capital: 'Douglas',
      languages: ['English', 'Manx'],
      population: 84497,
      flag: 'https://flagcdn.com/imn.svg',
      currency: 'British pound',
    },
    {
      name: 'Israel',
      capital: 'Jerusalem',
      languages: ['Hebrew (modern)', 'Arabic'],
      population: 8527400,
      flag: 'https://flagcdn.com/isr.svg',
      currency: 'Israeli new shekel',
    },
    {
      name: 'Italy',
      capital: 'Rome',
      languages: ['Italian'],
      population: 60665551,
      flag: 'https://flagcdn.com/ita.svg',
      currency: 'Euro',
    },
    {
      name: 'Jamaica',
      capital: 'Kingston',
      languages: ['English'],
      population: 2723246,
      flag: 'https://flagcdn.com/jam.svg',
      currency: 'Jamaican dollar',
    },
    {
      name: 'Japan',
      capital: 'Tokyo',
      languages: ['Japanese'],
      population: 126960000,
      flag: 'https://flagcdn.com/jpn.svg',
      currency: 'Japanese yen',
    },
    {
      name: 'Jersey',
      capital: 'Saint Helier',
      languages: ['English', 'French'],
      population: 100800,
      flag: 'https://flagcdn.com/jey.svg',
      currency: 'British pound',
    },
    {
      name: 'Jordan',
      capital: 'Amman',
      languages: ['Arabic'],
      population: 9531712,
      flag: 'https://flagcdn.com/jor.svg',
      currency: 'Jordanian dinar',
    },
    {
      name: 'Kazakhstan',
      capital: 'Astana',
      languages: ['Kazakh', 'Russian'],
      population: 17753200,
      flag: 'https://flagcdn.com/kaz.svg',
      currency: 'Kazakhstani tenge',
    },
    {
      name: 'Kenya',
      capital: 'Nairobi',
      languages: ['English', 'Swahili'],
      population: 47251000,
      flag: 'https://flagcdn.com/ken.svg',
      currency: 'Kenyan shilling',
    },
    {
      name: 'Kiribati',
      capital: 'South Tarawa',
      languages: ['English'],
      population: 113400,
      flag: 'https://flagcdn.com/kir.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Kuwait',
      capital: 'Kuwait City',
      languages: ['Arabic'],
      population: 4183658,
      flag: 'https://flagcdn.com/kwt.svg',
      currency: 'Kuwaiti dinar',
    },
    {
      name: 'Kyrgyzstan',
      capital: 'Bishkek',
      languages: ['Kyrgyz', 'Russian'],
      population: 6047800,
      flag: 'https://flagcdn.com/kgz.svg',
      currency: 'Kyrgyzstani som',
    },
    {
      name: "Lao People's Democratic Republic",
      capital: 'Vientiane',
      languages: ['Lao'],
      population: 6492400,
      flag: 'https://flagcdn.com/lao.svg',
      currency: 'Lao kip',
    },
    {
      name: 'Latvia',
      capital: 'Riga',
      languages: ['Latvian'],
      population: 1961600,
      flag: 'https://flagcdn.com/lva.svg',
      currency: 'Euro',
    },
    {
      name: 'Lebanon',
      capital: 'Beirut',
      languages: ['Arabic', 'French'],
      population: 5988000,
      flag: 'https://flagcdn.com/lbn.svg',
      currency: 'Lebanese pound',
    },
    {
      name: 'Lesotho',
      capital: 'Maseru',
      languages: ['English', 'Southern Sotho'],
      population: 1894194,
      flag: 'https://flagcdn.com/lso.svg',
      currency: 'Lesotho loti',
    },
    {
      name: 'Liberia',
      capital: 'Monrovia',
      languages: ['English'],
      population: 4615000,
      flag: 'https://flagcdn.com/lbr.svg',
      currency: 'Liberian dollar',
    },
    {
      name: 'Libya',
      capital: 'Tripoli',
      languages: ['Arabic'],
      population: 6385000,
      flag: 'https://flagcdn.com/lby.svg',
      currency: 'Libyan dinar',
    },
    {
      name: 'Liechtenstein',
      capital: 'Vaduz',
      languages: ['German'],
      population: 37623,
      flag: 'https://flagcdn.com/lie.svg',
      currency: 'Swiss franc',
    },
    {
      name: 'Lithuania',
      capital: 'Vilnius',
      languages: ['Lithuanian'],
      population: 2872294,
      flag: 'https://flagcdn.com/ltu.svg',
      currency: 'Euro',
    },
    {
      name: 'Luxembourg',
      capital: 'Luxembourg',
      languages: ['French', 'German', 'Luxembourgish'],
      population: 576200,
      flag: 'https://flagcdn.com/lux.svg',
      currency: 'Euro',
    },
    {
      name: 'Macao',
      capital: '',
      languages: ['Chinese', 'Portuguese'],
      population: 649100,
      flag: 'https://flagcdn.com/mac.svg',
      currency: 'Macanese pataca',
    },
    {
      name: 'Macedonia (the former Yugoslav Republic of)',
      capital: 'Skopje',
      languages: ['Macedonian'],
      population: 2058539,
      flag: 'https://flagcdn.com/mkd.svg',
      currency: 'Macedonian denar',
    },
    {
      name: 'Madagascar',
      capital: 'Antananarivo',
      languages: ['French', 'Malagasy'],
      population: 22434363,
      flag: 'https://flagcdn.com/mdg.svg',
      currency: 'Malagasy ariary',
    },
    {
      name: 'Malawi',
      capital: 'Lilongwe',
      languages: ['English', 'Chichewa'],
      population: 16832910,
      flag: 'https://flagcdn.com/mwi.svg',
      currency: 'Malawian kwacha',
    },
    {
      name: 'Malaysia',
      capital: 'Kuala Lumpur',
      languages: ['Malaysian'],
      population: 31405416,
      flag: 'https://flagcdn.com/mys.svg',
      currency: 'Malaysian ringgit',
    },
    {
      name: 'Maldives',
      capital: 'Malé',
      languages: ['Divehi'],
      population: 344023,
      flag: 'https://flagcdn.com/mdv.svg',
      currency: 'Maldivian rufiyaa',
    },
    {
      name: 'Mali',
      capital: 'Bamako',
      languages: ['French'],
      population: 18135000,
      flag: 'https://flagcdn.com/mli.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Malta',
      capital: 'Valletta',
      languages: ['Maltese', 'English'],
      population: 425384,
      flag: 'https://flagcdn.com/mlt.svg',
      currency: 'Euro',
    },
    {
      name: 'Marshall Islands',
      capital: 'Majuro',
      languages: ['English', 'Marshallese'],
      population: 54880,
      flag: 'https://flagcdn.com/mhl.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Martinique',
      capital: 'Fort-de-France',
      languages: ['French'],
      population: 378243,
      flag: 'https://flagcdn.com/mtq.svg',
      currency: 'Euro',
    },
    {
      name: 'Mauritania',
      capital: 'Nouakchott',
      languages: ['Arabic'],
      population: 3718678,
      flag: 'https://flagcdn.com/mrt.svg',
      currency: 'Mauritanian ouguiya',
    },
    {
      name: 'Mauritius',
      capital: 'Port Louis',
      languages: ['English'],
      population: 1262879,
      flag: 'https://flagcdn.com/mus.svg',
      currency: 'Mauritian rupee',
    },
    {
      name: 'Mayotte',
      capital: 'Mamoudzou',
      languages: ['French'],
      population: 226915,
      flag: 'https://flagcdn.com/myt.svg',
      currency: 'Euro',
    },
    {
      name: 'Mexico',
      capital: 'Mexico City',
      languages: ['Spanish'],
      population: 122273473,
      flag: 'https://flagcdn.com/mex.svg',
      currency: 'Mexican peso',
    },
    {
      name: 'Micronesia (Federated States of)',
      capital: 'Palikir',
      languages: ['English'],
      population: 102800,
      flag: 'https://flagcdn.com/fsm.svg',
      currency: '[D]',
    },
    {
      name: 'Moldova (Republic of)',
      capital: 'Chișinău',
      languages: ['Romanian'],
      population: 3553100,
      flag: 'https://flagcdn.com/mda.svg',
      currency: 'Moldovan leu',
    },
    {
      name: 'Monaco',
      capital: 'Monaco',
      languages: ['French'],
      population: 38400,
      flag: 'https://flagcdn.com/mco.svg',
      currency: 'Euro',
    },
    {
      name: 'Mongolia',
      capital: 'Ulan Bator',
      languages: ['Mongolian'],
      population: 3093100,
      flag: 'https://flagcdn.com/mng.svg',
      currency: 'Mongolian tögrög',
    },
    {
      name: 'Montenegro',
      capital: 'Podgorica',
      languages: ['Serbian', 'Bosnian', 'Albanian', 'Croatian'],
      population: 621810,
      flag: 'https://flagcdn.com/mne.svg',
      currency: 'Euro',
    },
    {
      name: 'Montserrat',
      capital: 'Plymouth',
      languages: ['English'],
      population: 4922,
      flag: 'https://flagcdn.com/msr.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Morocco',
      capital: 'Rabat',
      languages: ['Arabic'],
      population: 33337529,
      flag: 'https://flagcdn.com/mar.svg',
      currency: 'Moroccan dirham',
    },
    {
      name: 'Mozambique',
      capital: 'Maputo',
      languages: ['Portuguese'],
      population: 26423700,
      flag: 'https://flagcdn.com/moz.svg',
      currency: 'Mozambican metical',
    },
    {
      name: 'Myanmar',
      capital: 'Naypyidaw',
      languages: ['Burmese'],
      population: 51419420,
      flag: 'https://flagcdn.com/mmr.svg',
      currency: 'Burmese kyat',
    },
    {
      name: 'Namibia',
      capital: 'Windhoek',
      languages: ['English', 'Afrikaans'],
      population: 2324388,
      flag: 'https://flagcdn.com/nam.svg',
      currency: 'Namibian dollar',
    },
    {
      name: 'Nauru',
      capital: 'Yaren',
      languages: ['English', 'Nauruan'],
      population: 10084,
      flag: 'https://flagcdn.com/nru.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Nepal',
      capital: 'Kathmandu',
      languages: ['Nepali'],
      population: 28431500,
      flag: 'https://flagcdn.com/npl.svg',
      currency: 'Nepalese rupee',
    },
    {
      name: 'Netherlands',
      capital: 'Amsterdam',
      languages: ['Dutch'],
      population: 17019800,
      flag: 'https://flagcdn.com/nld.svg',
      currency: 'Euro',
    },
    {
      name: 'New Caledonia',
      capital: 'Nouméa',
      languages: ['French'],
      population: 268767,
      flag: 'https://flagcdn.com/ncl.svg',
      currency: 'CFP franc',
    },
    {
      name: 'New Zealand',
      capital: 'Wellington',
      languages: ['English', 'Māori'],
      population: 4697854,
      flag: 'https://flagcdn.com/nzl.svg',
      currency: 'New Zealand dollar',
    },
    {
      name: 'Nicaragua',
      capital: 'Managua',
      languages: ['Spanish'],
      population: 6262703,
      flag: 'https://flagcdn.com/nic.svg',
      currency: 'Nicaraguan córdoba',
    },
    {
      name: 'Niger',
      capital: 'Niamey',
      languages: ['French'],
      population: 20715000,
      flag: 'https://flagcdn.com/ner.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Nigeria',
      capital: 'Abuja',
      languages: ['English'],
      population: 186988000,
      flag: 'https://flagcdn.com/nga.svg',
      currency: 'Nigerian naira',
    },
    {
      name: 'Niue',
      capital: 'Alofi',
      languages: ['English'],
      population: 1470,
      flag: 'https://flagcdn.com/niu.svg',
      currency: 'New Zealand dollar',
    },
    {
      name: 'Norfolk Island',
      capital: 'Kingston',
      languages: ['English'],
      population: 2302,
      flag: 'https://flagcdn.com/nfk.svg',
      currency: 'Australian dollar',
    },
    {
      name: "Korea (Democratic People's Republic of)",
      capital: 'Pyongyang',
      languages: ['Korean'],
      population: 25281000,
      flag: 'https://flagcdn.com/prk.svg',
      currency: 'North Korean won',
    },
    {
      name: 'Northern Mariana Islands',
      capital: 'Saipan',
      languages: ['English', 'Chamorro'],
      population: 56940,
      flag: 'https://flagcdn.com/mnp.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Norway',
      capital: 'Oslo',
      languages: ['Norwegian', 'Norwegian Bokmål', 'Norwegian Nynorsk'],
      population: 5223256,
      flag: 'https://flagcdn.com/nor.svg',
      currency: 'Norwegian krone',
    },
    {
      name: 'Oman',
      capital: 'Muscat',
      languages: ['Arabic'],
      population: 4420133,
      flag: 'https://flagcdn.com/omn.svg',
      currency: 'Omani rial',
    },
    {
      name: 'Pakistan',
      capital: 'Islamabad',
      languages: ['English', 'Urdu'],
      population: 194125062,
      flag: 'https://flagcdn.com/pak.svg',
      currency: 'Pakistani rupee',
    },
    {
      name: 'Palau',
      capital: 'Ngerulmud',
      languages: ['English'],
      population: 17950,
      flag: 'https://flagcdn.com/plw.svg',
      currency: '[E]',
    },
    {
      name: 'Palestine, State of',
      capital: 'Ramallah',
      languages: ['Arabic'],
      population: 4682467,
      flag: 'https://flagcdn.com/pse.svg',
      currency: 'Israeli new sheqel',
    },
    {
      name: 'Panama',
      capital: 'Panama City',
      languages: ['Spanish'],
      population: 3814672,
      flag: 'https://flagcdn.com/pan.svg',
      currency: 'Panamanian balboa',
    },
    {
      name: 'Papua New Guinea',
      capital: 'Port Moresby',
      languages: ['English'],
      population: 8083700,
      flag: 'https://flagcdn.com/png.svg',
      currency: 'Papua New Guinean kina',
    },
    {
      name: 'Paraguay',
      capital: 'Asunción',
      languages: ['Spanish', 'Guaraní'],
      population: 6854536,
      flag: 'https://flagcdn.com/pry.svg',
      currency: 'Paraguayan guaraní',
    },
    {
      name: 'Peru',
      capital: 'Lima',
      languages: ['Spanish'],
      population: 31488700,
      flag: 'https://flagcdn.com/per.svg',
      currency: 'Peruvian sol',
    },
    {
      name: 'Philippines',
      capital: 'Manila',
      languages: ['English'],
      population: 103279800,
      flag: 'https://flagcdn.com/phl.svg',
      currency: 'Philippine peso',
    },
    {
      name: 'Pitcairn',
      capital: 'Adamstown',
      languages: ['English'],
      population: 56,
      flag: 'https://flagcdn.com/pcn.svg',
      currency: 'New Zealand dollar',
    },
    {
      name: 'Poland',
      capital: 'Warsaw',
      languages: ['Polish'],
      population: 38437239,
      flag: 'https://flagcdn.com/pol.svg',
      currency: 'Polish złoty',
    },
    {
      name: 'Portugal',
      capital: 'Lisbon',
      languages: ['Portuguese'],
      population: 10374822,
      flag: 'https://flagcdn.com/prt.svg',
      currency: 'Euro',
    },
    {
      name: 'Puerto Rico',
      capital: 'San Juan',
      languages: ['Spanish', 'English'],
      population: 3474182,
      flag: 'https://flagcdn.com/pri.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Qatar',
      capital: 'Doha',
      languages: ['Arabic'],
      population: 2587564,
      flag: 'https://flagcdn.com/qat.svg',
      currency: 'Qatari riyal',
    },
    {
      name: 'Republic of Kosovo',
      capital: 'Pristina',
      languages: ['Albanian', 'Serbian'],
      population: 1733842,
      flag: 'https://flagcdn.com/kos.svg',
      currency: 'Euro',
    },
    {
      name: 'Réunion',
      capital: 'Saint-Denis',
      languages: ['French'],
      population: 840974,
      flag: 'https://flagcdn.com/reu.svg',
      currency: 'Euro',
    },
    {
      name: 'Romania',
      capital: 'Bucharest',
      languages: ['Romanian'],
      population: 19861408,
      flag: 'https://flagcdn.com/rou.svg',
      currency: 'Romanian leu',
    },
    {
      name: 'Russian Federation',
      capital: 'Moscow',
      languages: ['Russian'],
      population: 146599183,
      flag: 'https://flagcdn.com/rus.svg',
      currency: 'Russian ruble',
    },
    {
      name: 'Rwanda',
      capital: 'Kigali',
      languages: ['Kinyarwanda', 'English', 'French'],
      population: 11553188,
      flag: 'https://flagcdn.com/rwa.svg',
      currency: 'Rwandan franc',
    },
    {
      name: 'Saint Barthélemy',
      capital: 'Gustavia',
      languages: ['French'],
      population: 9417,
      flag: 'https://flagcdn.com/blm.svg',
      currency: 'Euro',
    },
    {
      name: 'Saint Helena, Ascension and Tristan da Cunha',
      capital: 'Jamestown',
      languages: ['English'],
      population: 4255,
      flag: 'https://flagcdn.com/shn.svg',
      currency: 'Saint Helena pound',
    },
    {
      name: 'Saint Kitts and Nevis',
      capital: 'Basseterre',
      languages: ['English'],
      population: 46204,
      flag: 'https://flagcdn.com/kna.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Saint Lucia',
      capital: 'Castries',
      languages: ['English'],
      population: 186000,
      flag: 'https://flagcdn.com/lca.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Saint Martin (French part)',
      capital: 'Marigot',
      languages: ['English', 'French', 'Dutch'],
      population: 36979,
      flag: 'https://flagcdn.com/maf.svg',
      currency: 'Euro',
    },
    {
      name: 'Saint Pierre and Miquelon',
      capital: 'Saint-Pierre',
      languages: ['French'],
      population: 6069,
      flag: 'https://flagcdn.com/spm.svg',
      currency: 'Euro',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      capital: 'Kingstown',
      languages: ['English'],
      population: 109991,
      flag: 'https://flagcdn.com/vct.svg',
      currency: 'East Caribbean dollar',
    },
    {
      name: 'Samoa',
      capital: 'Apia',
      languages: ['Samoan', 'English'],
      population: 194899,
      flag: 'https://flagcdn.com/wsm.svg',
      currency: 'Samoan tālā',
    },
    {
      name: 'San Marino',
      capital: 'City of San Marino',
      languages: ['Italian'],
      population: 33005,
      flag: 'https://flagcdn.com/smr.svg',
      currency: 'Euro',
    },
    {
      name: 'Sao Tome and Principe',
      capital: 'São Tomé',
      languages: ['Portuguese'],
      population: 187356,
      flag: 'https://flagcdn.com/stp.svg',
      currency: 'São Tomé and Príncipe dobra',
    },
    {
      name: 'Saudi Arabia',
      capital: 'Riyadh',
      languages: ['Arabic'],
      population: 32248200,
      flag: 'https://flagcdn.com/sau.svg',
      currency: 'Saudi riyal',
    },
    {
      name: 'Senegal',
      capital: 'Dakar',
      languages: ['French'],
      population: 14799859,
      flag: 'https://flagcdn.com/sen.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Serbia',
      capital: 'Belgrade',
      languages: ['Serbian'],
      population: 7076372,
      flag: 'https://flagcdn.com/srb.svg',
      currency: 'Serbian dinar',
    },
    {
      name: 'Seychelles',
      capital: 'Victoria',
      languages: ['French', 'English'],
      population: 91400,
      flag: 'https://flagcdn.com/syc.svg',
      currency: 'Seychellois rupee',
    },
    {
      name: 'Sierra Leone',
      capital: 'Freetown',
      languages: ['English'],
      population: 7075641,
      flag: 'https://flagcdn.com/sle.svg',
      currency: 'Sierra Leonean leone',
    },
    {
      name: 'Singapore',
      capital: 'Singapore',
      languages: ['English', 'Malay', 'Tamil', 'Chinese'],
      population: 5535000,
      flag: 'https://flagcdn.com/sgp.svg',
      currency: 'Brunei dollar',
    },
    {
      name: 'Sint Maarten (Dutch part)',
      capital: 'Philipsburg',
      languages: ['Dutch', 'English'],
      population: 38247,
      flag: 'https://flagcdn.com/sxm.svg',
      currency: 'Netherlands Antillean guilder',
    },
    {
      name: 'Slovakia',
      capital: 'Bratislava',
      languages: ['Slovak'],
      population: 5426252,
      flag: 'https://flagcdn.com/svk.svg',
      currency: 'Euro',
    },
    {
      name: 'Slovenia',
      capital: 'Ljubljana',
      languages: ['Slovene'],
      population: 2064188,
      flag: 'https://flagcdn.com/svn.svg',
      currency: 'Euro',
    },
    {
      name: 'Solomon Islands',
      capital: 'Honiara',
      languages: ['English'],
      population: 642000,
      flag: 'https://flagcdn.com/slb.svg',
      currency: 'Solomon Islands dollar',
    },
    {
      name: 'Somalia',
      capital: 'Mogadishu',
      languages: ['Somali', 'Arabic'],
      population: 11079000,
      flag: 'https://flagcdn.com/som.svg',
      currency: 'Somali shilling',
    },
    {
      name: 'South Africa',
      capital: 'Pretoria',
      languages: [
        'Afrikaans',
        'English',
        'Southern Ndebele',
        'Southern Sotho',
        'Swati',
        'Tswana',
        'Tsonga',
        'Venda',
        'Xhosa',
        'Zulu',
      ],
      population: 55653654,
      flag: 'https://flagcdn.com/zaf.svg',
      currency: 'South African rand',
    },
    {
      name: 'South Georgia and the South Sandwich Islands',
      capital: 'King Edward Point',
      languages: ['English'],
      population: 30,
      flag: 'https://flagcdn.com/sgs.svg',
      currency: 'British pound',
    },
    {
      name: 'Korea (Republic of)',
      capital: 'Seoul',
      languages: ['Korean'],
      population: 50801405,
      flag: 'https://flagcdn.com/kor.svg',
      currency: 'South Korean won',
    },
    {
      name: 'South Sudan',
      capital: 'Juba',
      languages: ['English'],
      population: 12131000,
      flag: 'https://flagcdn.com/ssd.svg',
      currency: 'South Sudanese pound',
    },
    {
      name: 'Spain',
      capital: 'Madrid',
      languages: ['Spanish'],
      population: 46438422,
      flag: 'https://flagcdn.com/esp.svg',
      currency: 'Euro',
    },
    {
      name: 'Sri Lanka',
      capital: 'Colombo',
      languages: ['Sinhalese', 'Tamil'],
      population: 20966000,
      flag: 'https://flagcdn.com/lka.svg',
      currency: 'Sri Lankan rupee',
    },
    {
      name: 'Sudan',
      capital: 'Khartoum',
      languages: ['Arabic', 'English'],
      population: 39598700,
      flag: 'https://flagcdn.com/sdn.svg',
      currency: 'Sudanese pound',
    },
    {
      name: 'Suriname',
      capital: 'Paramaribo',
      languages: ['Dutch'],
      population: 541638,
      flag: 'https://flagcdn.com/sur.svg',
      currency: 'Surinamese dollar',
    },
    {
      name: 'Svalbard and Jan Mayen',
      capital: 'Longyearbyen',
      languages: ['Norwegian'],
      population: 2562,
      flag: 'https://flagcdn.com/sjm.svg',
      currency: 'Norwegian krone',
    },
    {
      name: 'Swaziland',
      capital: 'Lobamba',
      languages: ['English', 'Swati'],
      population: 1132657,
      flag: 'https://flagcdn.com/swz.svg',
      currency: 'Swazi lilangeni',
    },
    {
      name: 'Sweden',
      capital: 'Stockholm',
      languages: ['Swedish'],
      population: 9894888,
      flag: 'https://flagcdn.com/swe.svg',
      currency: 'Swedish krona',
    },
    {
      name: 'Switzerland',
      capital: 'Bern',
      languages: ['German', 'French', 'Italian'],
      population: 8341600,
      flag: 'https://flagcdn.com/che.svg',
      currency: 'Swiss franc',
    },
    {
      name: 'Syrian Arab Republic',
      capital: 'Damascus',
      languages: ['Arabic'],
      population: 18564000,
      flag: 'https://flagcdn.com/syr.svg',
      currency: 'Syrian pound',
    },
    {
      name: 'Taiwan',
      capital: 'Taipei',
      languages: ['Chinese'],
      population: 23503349,
      flag: 'https://flagcdn.com/twn.svg',
      currency: 'New Taiwan dollar',
    },
    {
      name: 'Tajikistan',
      capital: 'Dushanbe',
      languages: ['Tajik', 'Russian'],
      population: 8593600,
      flag: 'https://flagcdn.com/tjk.svg',
      currency: 'Tajikistani somoni',
    },
    {
      name: 'Tanzania, United Republic of',
      capital: 'Dodoma',
      languages: ['Swahili', 'English'],
      population: 55155000,
      flag: 'https://flagcdn.com/tza.svg',
      currency: 'Tanzanian shilling',
    },
    {
      name: 'Thailand',
      capital: 'Bangkok',
      languages: ['Thai'],
      population: 65327652,
      flag: 'https://flagcdn.com/tha.svg',
      currency: 'Thai baht',
    },
    {
      name: 'Timor-Leste',
      capital: 'Dili',
      languages: ['Portuguese'],
      population: 1167242,
      flag: 'https://flagcdn.com/tls.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Togo',
      capital: 'Lomé',
      languages: ['French'],
      population: 7143000,
      flag: 'https://flagcdn.com/tgo.svg',
      currency: 'West African CFA franc',
    },
    {
      name: 'Tokelau',
      capital: 'Fakaofo',
      languages: ['English'],
      population: 1411,
      flag: 'https://flagcdn.com/tkl.svg',
      currency: 'New Zealand dollar',
    },
    {
      name: 'Tonga',
      capital: "Nuku'alofa",
      languages: ['English', 'Tonga (Tonga Islands)'],
      population: 103252,
      flag: 'https://flagcdn.com/ton.svg',
      currency: 'Tongan paʻanga',
    },
    {
      name: 'Trinidad and Tobago',
      capital: 'Port of Spain',
      languages: ['English'],
      population: 1349667,
      flag: 'https://flagcdn.com/tto.svg',
      currency: 'Trinidad and Tobago dollar',
    },
    {
      name: 'Tunisia',
      capital: 'Tunis',
      languages: ['Arabic'],
      population: 11154400,
      flag: 'https://flagcdn.com/tun.svg',
      currency: 'Tunisian dinar',
    },
    {
      name: 'Turkey',
      capital: 'Ankara',
      languages: ['Turkish'],
      population: 78741053,
      flag: 'https://flagcdn.com/tur.svg',
      currency: 'Turkish lira',
    },
    {
      name: 'Turkmenistan',
      capital: 'Ashgabat',
      languages: ['Turkmen', 'Russian'],
      population: 4751120,
      flag: 'https://flagcdn.com/tkm.svg',
      currency: 'Turkmenistan manat',
    },
    {
      name: 'Turks and Caicos Islands',
      capital: 'Cockburn Town',
      languages: ['English'],
      population: 31458,
      flag: 'https://flagcdn.com/tca.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Tuvalu',
      capital: 'Funafuti',
      languages: ['English'],
      population: 10640,
      flag: 'https://flagcdn.com/tuv.svg',
      currency: 'Australian dollar',
    },
    {
      name: 'Uganda',
      capital: 'Kampala',
      languages: ['English', 'Swahili'],
      population: 33860700,
      flag: 'https://flagcdn.com/uga.svg',
      currency: 'Ugandan shilling',
    },
    {
      name: 'Ukraine',
      capital: 'Kiev',
      languages: ['Ukrainian'],
      population: 42692393,
      flag: 'https://flagcdn.com/ukr.svg',
      currency: 'Ukrainian hryvnia',
    },
    {
      name: 'United Arab Emirates',
      capital: 'Abu Dhabi',
      languages: ['Arabic'],
      population: 9856000,
      flag: 'https://flagcdn.com/are.svg',
      currency: 'United Arab Emirates dirham',
    },
    {
      name: 'United Kingdom of Great Britain and Northern Ireland',
      capital: 'London',
      languages: ['English'],
      population: 65110000,
      flag: 'https://flagcdn.com/gbr.svg',
      currency: 'British pound',
    },
    {
      name: 'United States of America',
      capital: 'Washington, D.C.',
      languages: ['English'],
      population: 323947000,
      flag: 'https://flagcdn.com/usa.svg',
      currency: 'United States dollar',
    },
    {
      name: 'Uruguay',
      capital: 'Montevideo',
      languages: ['Spanish'],
      population: 3480222,
      flag: 'https://flagcdn.com/ury.svg',
      currency: 'Uruguayan peso',
    },
    {
      name: 'Uzbekistan',
      capital: 'Tashkent',
      languages: ['Uzbek', 'Russian'],
      population: 31576400,
      flag: 'https://flagcdn.com/uzb.svg',
      currency: "Uzbekistani so'm",
    },
    {
      name: 'Vanuatu',
      capital: 'Port Vila',
      languages: ['Bislama', 'English', 'French'],
      population: 277500,
      flag: 'https://flagcdn.com/vut.svg',
      currency: 'Vanuatu vatu',
    },
    {
      name: 'Venezuela (Bolivarian Republic of)',
      capital: 'Caracas',
      languages: ['Spanish'],
      population: 31028700,
      flag: 'https://flagcdn.com/ven.svg',
      currency: 'Venezuelan bolívar',
    },
    {
      name: 'Viet Nam',
      capital: 'Hanoi',
      languages: ['Vietnamese'],
      population: 92700000,
      flag: 'https://flagcdn.com/vnm.svg',
      currency: 'Vietnamese đồng',
    },
    {
      name: 'Wallis and Futuna',
      capital: 'Mata-Utu',
      languages: ['French'],
      population: 11750,
      flag: 'https://flagcdn.com/wlf.svg',
      currency: 'CFP franc',
    },
    {
      name: 'Western Sahara',
      capital: 'El Aaiún',
      languages: ['Spanish'],
      population: 510713,
      flag: 'https://flagcdn.com/esh.svg',
      currency: 'Moroccan dirham',
    },
    {
      name: 'Yemen',
      capital: "Sana'a",
      languages: ['Arabic'],
      population: 27478000,
      flag: 'https://flagcdn.com/yem.svg',
      currency: 'Yemeni rial',
    },
    {
      name: 'Zambia',
      capital: 'Lusaka',
      languages: ['English'],
      population: 15933883,
      flag: 'https://flagcdn.com/zm.svg',
      currency: 'Zambian kwacha',
    },
    {
      name: 'Zimbabwe',
      capital: 'Harare',
      languages: ['English', 'Shona', 'Northern Ndebele'],
      population: 14240168,
      flag: 'https://flagcdn.com/zwe.svg',
      currency: 'Botswana pula',
    },
  ]

  